export { default as H1 } from "./GlobalComponents/H1";
export { default as H2 } from "./GlobalComponents/H2";
export { default as H3 } from "./GlobalComponents/H3";
export { default as H4 } from "./GlobalComponents/H4";
export { default as H5 } from "./GlobalComponents/H5";
export { default as SH1 } from "./GlobalComponents/SH1";
export { default as SH2 } from "./GlobalComponents/SH2";
export { default as NavText } from "./GlobalComponents/NavText";
export { default as P } from "./GlobalComponents/P";
